#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ca8fc4a87a65440c98d67e798199baa8" }
]

[assets]
directory = "./public"
